/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LibXJNI */

#ifndef _Included_LibXJNI
#define _Included_LibXJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LibXJNI
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LibXJNI_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
